import argparse
import json

from .core import check, coverage, generate, validate


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("command", choices=["validate", "generate", "check", "coverage"])
    args = parser.parse_args()
    if args.command == "validate":
        validate()
        print("upstream bundle valid")
    elif args.command == "generate":
        generate()
        print("generated by upstream pcbir.devicegen")
    elif args.command == "check":
        check()
        print("generated sources current")
    else:
        print(json.dumps(coverage(), indent=2))
